#数据源
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    driverClassName:  com.mysql.jdbc.Driver
    username: root
    password: hack
    testWhileIdle: true
    validationQuery: SELECT 1
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.solwMillis=5000;
    initialSize: 2
    maxActive: 20
    minIdle: 1
    maxWait: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    removeAbandoned: true
    removeAbandonedTimeout: 1200
    logAbandoned: true
#  http:
#    encoding:
#      force: true
#      charset: UTF-8
#      enabled: true
#  messages:
#    encoding: UTF-8


#数据操作接口
jpa:
  database: MySQL
  show-sql: true

#   服务器配置
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
