#数据源
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driverClassName:  com.mysql.jdbc.Driver
    username: root
    password: fZ8mzsbBWev7S9XCmIWAv1EPikYSdb3SYT+xPtuy9BaQN+EcSNLTQpBpU0iNhhDBFB7sdObwawWOVYDGqPB8lg==
    type: com.alibaba.druid.pool.DruidDataSource
    filters: config,stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.solwMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIvh0TJFg83DXAIywvdkcSph429+1ExYgoq/ViX+OGVZktc4Xx426c8ZeIk1QmkyGfdl4mGwlSv6vP6OgVlCkpcCAwEAAQ==
    initial-size: 2
    max-active: 20
    min-idle: 1
    max-wait: 60000
    validation-query: SELECT 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    time-between-eviction-runs-millis: 60000
    min-evictableidle-time-millis: 30000
    remove-abandoned: true
    remove-abandoned-timeout-millis: 1200
    log-abandoned: true
  profiles:
    include: shiro
#  http:
#    encoding:
#      force: true
#      charset: UTF-8
#      enabled: true
#  messages:
#    encoding: UTF-8

#mybatis
mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  type-aliases-package: com.hackdog.springbootlearn.pojo
  mapper-package: com.hackdog.springbootlearn.mapper

#数据操作接口
#jpa:
#  database: MySQL
#  show-sql: true

#   服务器配置
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
